CREATE OR ALTER VIEW dbo.SV__SD_VL06IF
AS
WITH ITEM_BASE AS (
    SELECT
        H.MANDT AS MANDT,
        H.VBELN AS DELIVERY,
        I.POSNR AS DELIVERY_ITEM,
        H.LFDAT AS DELIVERY_DATE,
        H.LIFNR AS SUPPLIER_RAW,
        CASE
            WHEN H.LIFNR IS NULL OR LTRIM(RTRIM(H.LIFNR)) = '' THEN NULL
            WHEN PATINDEX('%[^0]%', H.LIFNR) = 0 THEN '0'
            ELSE SUBSTRING(H.LIFNR, PATINDEX('%[^0]%', H.LIFNR), LEN(H.LIFNR))
        END AS SUPPLIER,
        LTRIM(RTRIM(
              COALESCE(V.NAME1, '')
            + CASE WHEN COALESCE(V.NAME2, '') = '' THEN '' ELSE ' ' + V.NAME2 END
            + CASE WHEN COALESCE(V.NAME3, '') = '' THEN '' ELSE ' ' + V.NAME3 END
            + CASE WHEN COALESCE(V.NAME4, '') = '' THEN '' ELSE ' ' + V.NAME4 END
        )) AS NAME_OF_VENDOR,
        H.VSTEL AS SHIPPING_POINT_RECEIVING_PT,
        H.ERNAM AS CREATED_BY,
        H.ERDAT AS CREATED_ON,
        H.LGNUM AS WAREHOUSE_NUMBER,
        I.LGORT AS STORAGE_LOCATION,
        H.LIFEX AS EXTERNAL_DELIVERY_ID,
        I.MATNR AS MATERIAL,
        I.ARKTX AS MATERIAL_DESCRIPTION,
        I.EAN11 AS EAN_UPC,
        I.VGBEL AS PURCHASING_DOCUMENT,
        I.VGPOS AS PURCHASING_DOCUMENT_ITEM,
        H.TRAID AS MEANS_OF_TRANSPORT,
        U.TRSTA AS TRANSPORTATION_STATUS,
        H.VLSTK AS DISTRIBUTION_STATUS,
        U.KOSTK AS PUTAWAY_STATUS,
        U.KOQUK AS PUTAWAY_CONFIRMATION_STATUS,
        U.WBSTK AS GOODS_MOVEMENT_STATUS,
        U.LVSTK AS WM_STATUS
    FROM dbo.LIKP AS H
    INNER JOIN dbo.VBUK AS U
        ON U.MANDT = H.MANDT
       AND U.VBELN = H.VBELN
    LEFT JOIN dbo.LIPS AS I
        ON I.MANDT = H.MANDT
       AND I.VBELN = H.VBELN
    LEFT JOIN dbo.LFA1 AS V
        ON V.MANDT = H.MANDT
       AND V.LIFNR = H.LIFNR
    WHERE H.VBTYP = '7'
      AND ISNULL(H.SPE_LOEKZ, '') = ''
)
SELECT DISTINCT
    MANDT,
    DELIVERY,
    DELIVERY_DATE,
    SUPPLIER,
    NAME_OF_VENDOR,
    SUPPLIER_RAW,
    SHIPPING_POINT_RECEIVING_PT,
    CREATED_BY,
    CREATED_ON,
    WAREHOUSE_NUMBER,
    STORAGE_LOCATION,
    EXTERNAL_DELIVERY_ID,
    MATERIAL,
    MATERIAL_DESCRIPTION,
    EAN_UPC,
    PURCHASING_DOCUMENT,
    PURCHASING_DOCUMENT_ITEM,
    MEANS_OF_TRANSPORT,
    TRANSPORTATION_STATUS,
    DISTRIBUTION_STATUS,
    PUTAWAY_STATUS,
    PUTAWAY_CONFIRMATION_STATUS,
    GOODS_MOVEMENT_STATUS,
    WM_STATUS
FROM ITEM_BASE;
GO





